version: "3"
services:
  sql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ultra@password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  api:
    image: ultra
    depends_on:
      - sql
    ports:
      - 80:3000
